---

- name: Install haproxy Package
  yum: name=haproxy state=present

- name: Open up firewall ports
  firewalld: service=http permanent=true state=enabled immediate=yes

- name: Start haproxy service
  service: name=haproxy state=started enabled=yes

- name: haproxy content
  template: dest=/etc/haproxy/haproxy.cfg src=/ansible/roles/haproxy/templates/haproxy.cfg.j2
  notify:
    - restart haproxy
