---
- hosts: packstack
  connection: local
  roles:
    - vm

- hosts: packstack
  gather_facts: false
  roles:
    - common
    - packstack

- hosts: packstack
  gather_facts: false
  connection: local
  roles:
    - packstack-demo
