---

- name: Update /etc/hosts
  lineinfile: dest=/etc/hosts line='{{ip}} {{name}}.{{domain}} {{name}}'

- name: Copy disk in place
  command: cp /var/lib/libvirt/images/template.qcow2 /var/lib/libvirt/images/{{ name }}.qcow2
  args:
    creates: /var/lib/libvirt/images/{{ name}}.qcow2

- name: Create second disk if needed
  command: qemu-img create -f qcow2 -o preallocation=metadata /var/lib/libvirt/images/{{ name }}-disk2.qcow2 {{ disk }}G
  when: disk is defined
  args:
    creates: /var/lib/libvirt/images/{{ name }}-disk2.qcow2

- name: Create VM
  virt: command=define name={{ name}} xml='{{ lookup('template', 'virt.xml.j2') }}'
  register: result
  #when: result|changed
  #args:
  #  creates: /var/lib/libvirt/images/{{ name }}-disk2.qcow2

- name: Inject SSH Key
  command: virt-customize -d {{ name }} --ssh-inject root:file:/root/.ssh/id_rsa.pub --selinux-relabel
  when: result|changed

- name: Set static IP
  command: virt-customize -d {{ name }} --run-command "echo IPADDR={{ ip }} >> /etc/sysconfig/network-scripts/ifcfg-eth0"
  when: result|changed
 
- name: Start VM
  virt: state=running name={{ name }}

- name: Wait for server to come back
  local_action: wait_for host={{ ansible_ssh_host }} state=started delay=30 timeout=300 port=22
