---

- name: Open up firewall ports
  firewalld: port={{ item }} permanent=true state=enabled immediate=yes
  with_items:
    - 6789/tcp
    - 8002/tcp
    - 6800-7300/tcp
    - 7480/tcp
    - 80/tcp
    - 443/tcp
  tags: ceph-common

- name: Add ceph user
  user: 
    name: ceph
    generate_ssh_key: yes
  tags: ceph-common

- name: Copy ssh key to ceph nodes
  copy: 
    src: /ansible/roles/ceph-man/files/id_rsa.pub
    dest: /home/ceph/.ssh/authorized_keys
  tags: ceph-common

- name: Setup sudoers file
  copy: 
    content: "ceph ALL=(root) NOPASSWD:ALL" 
    dest: /etc/sudoers.d/stack
    force: no 
    group: root 
    owner: root 
    mode: 0644
  tags: ceph-common

