---

- name: Update /etc/hosts
  lineinfile: dest=/etc/hosts line='{{ inventory_hostname }} {{ ansible_host }}.{{domain}} {{ ansible_host }}'
  tags: vm

- name: Copy disk in place
  command: cp -p /var/lib/libvirt/images/{{ template }}.qcow2 /var/lib/libvirt/images/{{ ansible_host }}.qcow2 
  args:
    creates: /var/lib/libvirt/images/{{ ansible_host }}.qcow2
  tags: vm

- name: Create second disk if needed
  command: qemu-img create -f qcow2 -o preallocation=metadata /var/lib/libvirt/images/{{ ansible_host }}-disk2.qcow2 {{ disk }}G
  when: disk is defined
  args:
    creates: /var/lib/libvirt/images/{{ ansible_host }}-disk2.qcow2
  tags: vm

- name: Create VM
  virt: command=define name={{ ansible_host }} xml='{{ lookup('template', 'virt.xml.j2') }}'
  register: result
  tags: vm

- name: Get Atomic dir
  shell: "guestfish add /var/lib/libvirt/images/{{ ansible_host }}.qcow2 : run : mount /dev/rhelah/root / : ls {{ ostree_dir }} | grep -v origin"
  register: atomic_dir
  when: result|changed
  tags: vm

- name: Generate Config file
  template: 
    src: ifcfg-eth0.j2
    dest: /tmp/ifcfg-eth0
  when: result|changed
  tags: vm

- name: Set static IP
  shell: "guestfish add /var/lib/libvirt/images/{{ ansible_host }}.qcow2 : run : mount /dev/rhelah/root / : copy-in /tmp/ifcfg-eth0  /{{ ostree_dir }}/{{ atomic_dir.stdout }}/etc/sysconfig/network-scripts"
  when: result|changed
  tags: vm

- name: Remove /tmp/ifcfg-eth0
  file:
    path: /tmp/ifcfg-eth0
    state: absent
  tags: vm

- name: Start VM
  virt: state=running name={{ ansible_host }}
  tags: vm

- name: Wait for server to come back
  wait_for: host={{ ansible_ssh_host }} delay=10 timeout=300 port=22
  connection: local
  tags: vm
