---

- name: Enable OCP repos
  yum_repository: name={{ item }} description={{ item }} baseurl=http://192.168.122.1/repo/{{ item }}/Packages gpgcheck=no file=local
  with_items:
    - rhel-7-server-ose-3.5-rpms
    - rhel-7-fast-datapath-rpms
    - rhel-7-server-extras-rpms

- name: Install required Packages
  yum: name={{ item }} state=present
  with_items:
    - wget
    - net-tools
    - git
    - bind-utils
    - iptables-services
    - bridge-utils
    - bash-completion

- name: Install OCP Packages
  yum: name={{ item }} state=present
  with_items:
    - atomic-openshift-utils
    - atomic-openshift-excluder
    - atomic-openshift-docker-excluder

- name: Install docker 
  yum: name=docker state=present

- name: Remove OCP packages exclude
  shell: atomic-openshift-excluder unexclude

- name: define OCP disks
  lineinfile: path=/etc/sysconfig/docker-storage-setup line={{ item }}
  with_items:
    - "DEVS=/dev/vdb"
    - "VG=docker-vg"

- name: create OCP disk
  shell:  docker-storage-setup
  args:
    create: /dev/docker-vg


