---

- name: Install keepalived Package
  yum: name=keepalived state=present

- name: Install psmisc
  yum: name=psmisc state=present

- name: Open up firewall ports
  firewalld: service=http permanent=true state=enabled immediate=yes

- name: Start keepalived service
  service: name=keepalived state=started enabled=yes

- name: keepalived config
  template: dest=/etc/keepalived/keepalived.conf src=/ansible/roles/keepalived/templates/keepalived.conf.j2
  notify:
    - restart keepalived
