---

- hosts: ocp-master
  serial:
  - 1
  
  tasks:

  - name: Reboot server
    shell: sleep 2 && reboot
    async: 1
    poll: 0
    ignore_errors: true

  - name: Wait for server to come back
    local_action: wait_for host={{ inventory_hostname }} state=started delay=10 timeout=300 port=22
