---

- hosts: satellite
  become: true
  become_user: root
  vars: 
    somevar: "value"
  vars_prompt: 
    - name: "ldap_password"
      prompt: "Enter LDAP Password"
    - name: "old_sat_password"
      prompt: "Enter Old Admin Sat Password"
    - name: "new_sat_password"
      prompt: "Enter New Admin Sat Password"

  
  tasks:

  - name: Error if LDAP Password not set
    fail: msg="LDAP Password not set"
    failed_when: ldap_password  == ""

  - name: Error if Old Sat Password not set
    fail: msg="Old Sat Password not set"
    failed_when: old_sat_password  == ""

  - name: Error if new Sat Password not set
    fail: msg="new new Password not set"
    failed_when: new_sat_password  == ""

  - name: Get LDAP ID's
    shell: hammer -u admin -p {{ old_sat_password }} auth-source ldap list | grep SourceLdap | awk '{print $1'} 
    register: ldap_id

  - name: Error if LDAP ID's not set
    fail: msg="Didn't get any LDAP ID's"
    failed_when: ldap_id.stdout  == ""

  - name: Set Admin password
    shell: hammer -u admin -p {{ old_sat_password }} user update --login admin --password {{ new_sat_password }}

  - name: Set LDAP Password
    shell: hammer -u admin -p {{ new_sat_password }} auth-source ldap update --id {{ item }} --account-password {{ ldap_password }}
    with_items: "{{ ldap_id.stdout_lines }}"

  - name: Get virt-who-password
    script: /ansible/plays/virt-who-script.sh {{ new_sat_password }}  | tail -1
    register: vwho

  - name: replace line in vwho file
    replace: dest=/etc/virt-who.d/pat.conf regexp='^encrypted_password.*' replace='encrypted_password={{ vwho.stdout }}'
    notify: virt-who

  handlers:
  
  - name: virt-who
    service: name=virt-who state=restarted
